In [39]:
import pandas as pd
import numpy as np


In [40]:
df = pd.read_csv("car_data.csv")

In [41]:
df

Car_Name  Year  Selling_Price  Present_Price  Kms_Driven Fuel_Type  \
0       ritz  2014           3.35           5.59       27000    Petrol   
1        sx4  2013           4.75           9.54       43000    Diesel   
2       ciaz  2017           7.25           9.85        6900    Petrol   
3    wagon r  2011           2.85           4.15        5200    Petrol   
4      swift  2014           4.60           6.87       42450    Diesel   
..       ...   ...            ...            ...         ...       ...   
296     city  2016           9.50          11.60       33988    Diesel   
297     brio  2015           4.00           5.90       60000    Petrol   
298     city  2009           3.35          11.00       87934    Petrol   
299     city  2017          11.50          12.50        9000    Diesel   
300     brio  2016           5.30           5.90        5464    Petrol   

    Seller_Type Transmission  Owner  
0        Dealer       Manual      0  
1        Dealer       Manual      0  
2        Dealer       Manual      0  
3        Dealer       Manual      0  
4        Dealer       Manual      0  
..          ...          ...    ...  
296      Dealer       Manual      0  
297      Dealer       Manual      0  
298      Dealer       Manual      0  
299      Dealer       Manual      0  
300      Dealer       Manual      0  

[301 rows x 9 columns]

In [42]:
df.head()

Car_Name  Year  Selling_Price  Present_Price  Kms_Driven Fuel_Type  \
0     ritz  2014           3.35           5.59       27000    Petrol   
1      sx4  2013           4.75           9.54       43000    Diesel   
2     ciaz  2017           7.25           9.85        6900    Petrol   
3  wagon r  2011           2.85           4.15        5200    Petrol   
4    swift  2014           4.60           6.87       42450    Diesel   

  Seller_Type Transmission  Owner  
0      Dealer       Manual      0  
1      Dealer       Manual      0  
2      Dealer       Manual      0  
3      Dealer       Manual      0  
4      Dealer       Manual      0

In [43]:
df.shape

(301, 9)

In [44]:
df.isnull().sum()

Car_Name         0
Year             0
Selling_Price    0
Present_Price    0
Kms_Driven       0
Fuel_Type        0
Seller_Type      0
Transmission     0
Owner            0
dtype: int64

In [45]:
X= df.drop("Selling_Price", axis=1)

In [46]:
X

Car_Name  Year  Present_Price  Kms_Driven Fuel_Type Seller_Type  \
0       ritz  2014           5.59       27000    Petrol      Dealer   
1        sx4  2013           9.54       43000    Diesel      Dealer   
2       ciaz  2017           9.85        6900    Petrol      Dealer   
3    wagon r  2011           4.15        5200    Petrol      Dealer   
4      swift  2014           6.87       42450    Diesel      Dealer   
..       ...   ...            ...         ...       ...         ...   
296     city  2016          11.60       33988    Diesel      Dealer   
297     brio  2015           5.90       60000    Petrol      Dealer   
298     city  2009          11.00       87934    Petrol      Dealer   
299     city  2017          12.50        9000    Diesel      Dealer   
300     brio  2016           5.90        5464    Petrol      Dealer   

    Transmission  Owner  
0         Manual      0  
1         Manual      0  
2         Manual      0  
3         Manual      0  
4         Manual      0  
..           ...    ...  
296       Manual      0  
297       Manual      0  
298       Manual      0  
299       Manual      0  
300       Manual      0  

[301 rows x 8 columns]

In [47]:
y= df["Selling_Price"]

In [48]:
X["Year"]= 2023 - X["Year"]

In [49]:
X

Car_Name  Year  Present_Price  Kms_Driven Fuel_Type Seller_Type  \
0       ritz     9           5.59       27000    Petrol      Dealer   
1        sx4    10           9.54       43000    Diesel      Dealer   
2       ciaz     6           9.85        6900    Petrol      Dealer   
3    wagon r    12           4.15        5200    Petrol      Dealer   
4      swift     9           6.87       42450    Diesel      Dealer   
..       ...   ...            ...         ...       ...         ...   
296     city     7          11.60       33988    Diesel      Dealer   
297     brio     8           5.90       60000    Petrol      Dealer   
298     city    14          11.00       87934    Petrol      Dealer   
299     city     6          12.50        9000    Diesel      Dealer   
300     brio     7           5.90        5464    Petrol      Dealer   

    Transmission  Owner  
0         Manual      0  
1         Manual      0  
2         Manual      0  
3         Manual      0  
4         Manual      0  
..           ...    ...  
296       Manual      0  
297       Manual      0  
298       Manual      0  
299       Manual      0  
300       Manual      0  

[301 rows x 8 columns]

In [50]:
X.drop(["Present_Price","Car_Name"], axis=1 , inplace=True)

In [51]:
X

Year  Kms_Driven Fuel_Type Seller_Type Transmission  Owner
0       9       27000    Petrol      Dealer       Manual      0
1      10       43000    Diesel      Dealer       Manual      0
2       6        6900    Petrol      Dealer       Manual      0
3      12        5200    Petrol      Dealer       Manual      0
4       9       42450    Diesel      Dealer       Manual      0
..    ...         ...       ...         ...          ...    ...
296     7       33988    Diesel      Dealer       Manual      0
297     8       60000    Petrol      Dealer       Manual      0
298    14       87934    Petrol      Dealer       Manual      0
299     6        9000    Diesel      Dealer       Manual      0
300     7        5464    Petrol      Dealer       Manual      0

[301 rows x 6 columns]

In [52]:
X["Fuel_Type"].unique()

array(['Petrol', 'Diesel', 'CNG'], dtype=object)

In [53]:
X["Seller_Type"].unique()

array(['Dealer', 'Individual'], dtype=object)

In [54]:
X["Transmission"].unique()

array(['Manual', 'Automatic'], dtype=object)

In [65]:
X["Owner"].unique()

array([0, 1, 3], dtype=int64)

In [55]:
X= pd.get_dummies(data=X ,columns=["Fuel_Type" ,"Seller_Type", "Transmission"] , drop_first=True )

In [56]:
X


Year  Kms_Driven  Owner  Fuel_Type_Diesel  Fuel_Type_Petrol  \
0       9       27000      0                 0                 1   
1      10       43000      0                 1                 0   
2       6        6900      0                 0                 1   
3      12        5200      0                 0                 1   
4       9       42450      0                 1                 0   
..    ...         ...    ...               ...               ...   
296     7       33988      0                 1                 0   
297     8       60000      0                 0                 1   
298    14       87934      0                 0                 1   
299     6        9000      0                 1                 0   
300     7        5464      0                 0                 1   

     Seller_Type_Individual  Transmission_Manual  
0                         0                    1  
1                         0                    1  
2                         0                    1  
3                         0                    1  
4                         0                    1  
..                      ...                  ...  
296                       0                    1  
297                       0                    1  
298                       0                    1  
299                       0                    1  
300                       0                    1  

[301 rows x 7 columns]

In [58]:
from sklearn.preprocessing import MinMaxScaler


In [59]:
scaler=MinMaxScaler()

In [67]:
X["Year"] = scaler.fit_transform(X[["Year"]])

In [68]:
X["Kms_Driven"] = scaler.fit_transform(X[["Kms_Driven"]])

In [69]:
X["Owner"] = scaler.fit(X[["Owner"]])

In [ ]:
X 

In [ ]:
X["Owner"] = scaler.fit_transform(X[["Owner"]])

In [70]:
X

Year  Kms_Driven  Owner  Fuel_Type_Diesel  Fuel_Type_Petrol  \
0    0.266667    0.053053    0.0                 0                 1   
1    0.333333    0.085085    0.0                 1                 0   
2    0.066667    0.012813    0.0                 0                 1   
3    0.466667    0.009409    0.0                 0                 1   
4    0.266667    0.083984    0.0                 1                 0   
..        ...         ...    ...               ...               ...   
296  0.133333    0.067043    0.0                 1                 0   
297  0.200000    0.119119    0.0                 0                 1   
298  0.600000    0.175043    0.0                 0                 1   
299  0.066667    0.017017    0.0                 1                 0   
300  0.133333    0.009938    0.0                 0                 1   

     Seller_Type_Individual  Transmission_Manual  
0                         0                    1  
1                         0                    1  
2                         0                    1  
3                         0                    1  
4                         0                    1  
..                      ...                  ...  
296                       0                    1  
297                       0                    1  
298                       0                    1  
299                       0                    1  
300                       0                    1  

[301 rows x 7 columns]

In [71]:
X["Owner"].unique()

array([0.        , 0.33333333, 1.        ])

In [72]:
X.describe()

Year  Kms_Driven       Owner  Fuel_Type_Diesel  Fuel_Type_Petrol  \
count  301.000000  301.000000  301.000000        301.000000        301.000000   
mean     0.291473    0.072967    0.014396          0.199336          0.794020   
std      0.192770    0.077852    0.082638          0.400166          0.405089   
min      0.000000    0.000000    0.000000          0.000000          0.000000   
25%      0.133333    0.029029    0.000000          0.000000          1.000000   
50%      0.266667    0.063063    0.000000          0.000000          1.000000   
75%      0.400000    0.096631    0.000000          0.000000          1.000000   
max      1.000000    1.000000    1.000000          1.000000          1.000000   

       Seller_Type_Individual  Transmission_Manual  
count              301.000000           301.000000  
mean                 0.352159             0.867110  
std                  0.478439             0.340021  
min                  0.000000             0.000000  
25%                  0.000000             1.000000  
50%                  0.000000             1.000000  
75%                  1.000000             1.000000  
max                  1.000000             1.000000

# Without train_test_split model working:


In [88]:
 from  sklearn.linear_model import LinearRegression 

In [89]:
model=LinearRegression()

In [90]:
model.fit(X , y)

LinearRegression()

In [91]:
model.score(X,y)

0.5816549394812498

In [93]:
y_prediction= model.predict(X)
y_prediction

array([ 4.74569690e+00,  9.13895127e+00,  5.77497331e+00,  3.89205178e+00,
        9.45626459e+00,  1.08855519e+01,  5.09509332e+00,  9.80908561e+00,
        1.01792392e+01,  9.77162040e+00,  5.79494666e+00,  9.73543364e+00,
        9.73826707e+00,  5.06489647e+00,  2.95928367e+00,  1.00839750e+01,
        9.77450846e+00,  1.00839750e+01,  3.76040127e+00,  3.42512909e+00,
        5.38409605e+00,  5.79383586e+00,  8.33152675e+00,  4.66907302e+00,
        4.30544585e+00,  3.83001495e+00,  4.31274357e+00,  1.52051344e+00,
        3.41213489e+00,  9.76058371e+00,  8.78856980e+00,  3.68665956e+00,
        9.47072588e+00,  9.44557581e+00,  9.44557581e+00,  2.43959873e+00,
        4.96946454e+00, -3.35403504e+00,  5.44664007e+00,  1.13390130e+00,
        1.00133534e+01,  4.66309569e+00,  2.72570750e+00,  9.44230630e+00,
        4.01927251e+00,  9.42325917e+00,  4.27336694e+00,  2.06634996e+00,
        5.06544139e+00,  1.02760659e+01,  1.31925496e+01,  1.44088042e+01,
        1.51436120e+01,  

In [73]:
from sklearn.model_selection import train_test_split

In [74]:
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.33, random_state=42)

In [78]:
len(X_train)

201

In [79]:
len(y_train)

201

In [75]:
 from  sklearn.linear_model import LinearRegression 

In [76]:
model=LinearRegression()

In [80]:
model.fit(X_train , y_train)

LinearRegression()

In [82]:
model.score(X_test , y_test)

0.6277335827814441

In [83]:
y_pred = model.predict(X_test)

In [87]:
 y_pred[0:3]

array([5.55891467, 5.13809034, 9.24487324])