In [22]:
import numpy as np

In [24]:
x= [1,2,3,4,5,6]
y=[3,4,2,4,5,7]
x = np.array([1,2,3,4,5,6]).reshape(6,1)
x

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [25]:
from sklearn.linear_model import LinearRegression

In [26]:
model= LinearRegression()

In [27]:
model.fit(x,y)

LinearRegression()

In [28]:
model.coef_

array([0.71428571])

In [19]:
model.intercept_

2.4

In [29]:
import numpy as np

# Your data
x = np.array([1, 2, 3, 4, 5])
y = np.array([3, 4, 2, 4, 5])

# Calculate mean of x and y
mean_x = np.mean(x)
mean_y = np.mean(y)

# Calculate xi - xmean and yi - ymean
x_diff = x - mean_x
y_diff = y - mean_y

# Calculate the slope (m)
slope = np.sum(x_diff * y_diff) / np.sum(x_diff**2)

# Calculate the intercept (b)
intercept = mean_y - slope * mean_x

# Print the results
print("Mean of x:", mean_x)
print("Mean of y:", mean_y)
print("x - mean_x:", x_diff)
print("y - mean_y:", y_diff)
print("Slope (m):", slope)
print("Intercept (b):", intercept)


Mean of x: 3.0
Mean of y: 3.6
x - mean_x: [-2. -1.  0.  1.  2.]
y - mean_y: [-0.6  0.4 -1.6  0.4  1.4]
Slope (m): 0.4
Intercept (b): 2.4


In [31]:
x_diff.sum()

0.0

In [32]:
np.sum(x_diff * y_diff)

4.0

In [33]:
np.sum(x_diff**2)

10.0

In [36]:
x_diff

array([-2., -1.,  0.,  1.,  2.])