In [1]:
import numpy as np

In [3]:
cell=np.array([[6, 7, 8],
       [1, 2, 3],
       [4, 5, 6]])  


In [5]:
for row in cell:  
    print(row)  
    

[6 7 8]
[1 2 3]
[4 5 6]


In [6]:
for row in cell:
    for no in row:
        print(no)

6
7
8
1
2
3
4
5
6


In [21]:
a=np.array([1,2,3,4,6,7])
b=np.array([8,9,10,11,12,13])

In [22]:
for cell in a.flatten():
    print(cell)

1
2
3
4
6
7


In [23]:
for x,y in np.nditer([a,b]):
    print(x,y)

1 8
2 9
3 10
4 11
6 12
7 13
