# Numpy introduction

In [1]:
import numpy as np 


In [42]:
a1=np.array([1,2,3,4,5])

In [44]:
a1.itemsize

4

In [45]:
a2=np.array([6,7,8,9,10],dtype=float)

In [46]:
a2.itemsize

8

In [20]:
np.array([6,7,8,9,10],dtype=complex)

array([ 6.+0.j,  7.+0.j,  8.+0.j,  9.+0.j, 10.+0.j])

In [21]:
np.array([6,7,8,9,10],dtype=str)

array(['6', '7', '8', '9', '10'], dtype='<U2')

In [22]:
a=np.array([1,2,3,4,5])

In [31]:
a

array([1, 2, 3, 4, 5])

In [73]:
a.astype('float')

array([1., 2., 3., 4., 5.])

In [32]:
a.ndim


1

In [61]:
b=np.arange(1,51)

In [62]:
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [66]:
b.reshape(2,5,5)

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25]],

       [[26, 27, 28, 29, 30],
        [31, 32, 33, 34, 35],
        [36, 37, 38, 39, 40],
        [41, 42, 43, 44, 45],
        [46, 47, 48, 49, 50]]])

In [86]:
b.size

50

In [87]:
b.shape

(50,)

In [93]:
a=np.arange(1,11).reshape(5,2)

In [94]:
a

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [96]:
a.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [108]:
a.flatten(order='f')

array([ 1,  3,  5,  7,  9,  2,  4,  6,  8, 10])

In [110]:
a.transpose()

array([[ 1,  3,  5,  7,  9],
       [ 2,  4,  6,  8, 10]])

## Generic funtion in Numpy

In [111]:
np.ones((5,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [112]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [113]:
np.arange(5,100,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85,
       90, 95])

In [116]:
np.linspace(1,5,5)

array([1., 2., 3., 4., 5.])

In [123]:
a=np.array([1,2,3,4,5])

In [124]:
b=np.array([6,7,8,9,10])

In [125]:
a

array([1, 2, 3, 4, 5])

In [126]:
b

array([ 6,  7,  8,  9, 10])

In [127]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

In [128]:
np.add(a,b)

array([ 7,  9, 11, 13, 15])

In [130]:
np.subtract(a,b)

array([-5, -5, -5, -5, -5])

In [131]:
np.divide(a,b)

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [133]:
np.argmax(a)

4

In [134]:
np.argmin(a)

0

In [136]:
np.mean(a)

3.0

##  Mathematical funtion axis =1:col & axis=0:row

In [150]:
a=np.array([[1, 2],
       [3, 4]])

b=np.array([[5, 6],
       [7, 8]])

In [158]:
a.min(axis=0)

array([1, 2])

In [155]:
a.max(axis=0)

array([3, 4])

In [157]:
a.sum(axis=0)

array([4, 6])

In [160]:
b

array([[5, 6],
       [7, 8]])

In [161]:
a+b

array([[ 6,  8],
       [10, 12]])

In [162]:
a-b

array([[-4, -4],
       [-4, -4]])

In [163]:
a/b

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [164]:
a*a

array([[ 1,  4],
       [ 9, 16]])

In [165]:
a.dot(b)

array([[19, 22],
       [43, 50]])