In [1]:
import numpy as np 

## slicing on 2D array

In [13]:
a=np.arange(1,10).reshape(3,3)

In [14]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
a[0]

array([1, 2, 3])

In [16]:
a[0:2,1:]

array([[2, 3],
       [5, 6]])

In [17]:
a[1:,1:]

array([[5, 6],
       [8, 9]])

In [18]:
a[0,2]

3

## Slicing for 3D array

In [19]:
b=np.arange(1,19).reshape(2,3,3)

In [20]:
b


array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [21]:
b[0,1,2]

6

In [23]:
b[1,0:2,1:]

array([[11, 12],
       [14, 15]])

In [24]:
b[1,2,0:2]

array([16, 17])

In [25]:
b[1,2,2]

18

In [27]:
b[1,1:,2]

array([15, 18])

## Stacking and spliting array

In [30]:
a=np.arange(1,10).reshape(3,3)
b=np.arange(11,20).reshape(3,3)

In [31]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
b

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [34]:
np.vstack((a,b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [35]:
np.hstack((a,b))

array([[ 1,  2,  3, 11, 12, 13],
       [ 4,  5,  6, 14, 15, 16],
       [ 7,  8,  9, 17, 18, 19]])

In [36]:
np. concatenate((a,b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [38]:
np. concatenate((a,b),axis=1)

array([[ 1,  2,  3, 11, 12, 13],
       [ 4,  5,  6, 14, 15, 16],
       [ 7,  8,  9, 17, 18, 19]])

In [40]:
np.hsplit(a,3)

[array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]]),
 array([[3],
        [6],
        [9]])]

In [41]:
np.vsplit(a,3)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]

In [42]:
a,b,c=np.vsplit(a,3)

In [43]:
a

array([[1, 2, 3]])

In [44]:
b

array([[4, 5, 6]])

In [45]:
c

array([[7, 8, 9]])

In [46]:
e=np.array([1,2,3,4,5,6,7,8,9])

In [47]:
e

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
np.split(e,[3,6])

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]

In [53]:
np.split(e,[1,4])

[array([1]), array([2, 3, 4]), array([5, 6, 7, 8, 9])]