In [2]:
import numpy as np
import pandas as pd
a=np.array([[5, 1,6],
       [4, 3,4],
       [2, 6,8],
       [8, 7,2
       ]])

In [3]:
df=pd.DataFrame(a)

In [4]:
df


0  1  2
0  5  1  6
1  4  3  4
2  2  6  8
3  8  7  2

In [5]:
df.min(axis=0)

0    2
1    1
2    2
dtype: int32

In [6]:
b=np.array([[6, 7, 8],
       [1, 2, 3],
       [4, 5, 6]])

In [38]:
b.itemsize

4

In [8]:
b[0:3,2]

array([8, 3, 6])

In [9]:
b[0:2,1]

array([7, 2])

In [35]:
b.iteamsize()

AttributeError: 'numpy.ndarray' object has no attribute 'iteamsize'

In [19]:
df[0].astype('complex')

0    5.0+0.0j
1    4.0+0.0j
2    2.0+0.0j
3    8.0+0.0j
Name: 0, dtype: complex128

In [33]:
df[0][1].it

AttributeError: 'numpy.int32' object has no attribute 'iteamsize'

In [40]:
b.itemsize

4

In [41]:
b.ndim

2

In [43]:
b

array([[6, 7, 8],
       [1, 2, 3],
       [4, 5, 6]])

In [49]:
b.flatten('k')

array([6, 7, 8, 1, 2, 3, 4, 5, 6])

In [60]:
np.zeros((2,2,4,2,2,3))

array([[[[[[0., 0., 0.],
           [0., 0., 0.]],

          [[0., 0., 0.],
           [0., 0., 0.]]],


         [[[0., 0., 0.],
           [0., 0., 0.]],

          [[0., 0., 0.],
           [0., 0., 0.]]],


         [[[0., 0., 0.],
           [0., 0., 0.]],

          [[0., 0., 0.],
           [0., 0., 0.]]],


         [[[0., 0., 0.],
           [0., 0., 0.]],

          [[0., 0., 0.],
           [0., 0., 0.]]]],



        [[[[0., 0., 0.],
           [0., 0., 0.]],

          [[0., 0., 0.],
           [0., 0., 0.]]],


         [[[0., 0., 0.],
           [0., 0., 0.]],

          [[0., 0., 0.],
           [0., 0., 0.]]],


         [[[0., 0., 0.],
           [0., 0., 0.]],

          [[0., 0., 0.],
           [0., 0., 0.]]],


         [[[0., 0., 0.],
           [0., 0., 0.]],

          [[0., 0., 0.],
           [0., 0., 0.]]]]],




       [[[[[0., 0., 0.],
           [0., 0., 0.]],

          [[0., 0., 0.],
           [0., 0., 0.]]],


         [[[0., 0., 0.],
           [0.,

In [61]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [62]:
b

array([[6, 7, 8],
       [1, 2, 3],
       [4, 5, 6]])

In [67]:
for a in b.flatten('f'):
    print(a)

6
1
4
7
2
5
8
3
6
