In [29]:
import numpy as np
import pandas as pd
a=np.array([[5, 1,6],
       [4, 3,4],
       [2, 6,8],
       [8, 7,2
       ]])

In [30]:
df=pd.DataFrame(a)

In [31]:
df


0  1  2
0  5  1  6
1  4  3  4
2  2  6  8
3  8  7  2

In [33]:
df.min(axis=0)

0    2
1    1
2    2
dtype: int32

In [34]:
b=np.array([[6, 7, 8],
       [1, 2, 3],
       [4, 5, 6]])

In [35]:
b

array([[6, 7, 8],
       [1, 2, 3],
       [4, 5, 6]])

In [36]:
b[0:3,2]

array([8, 3, 6])

In [37]:
b[0:2,1]

array([7, 2])