In [4]:

import numpy as np


In [2]:
a=np.array([[6,7,8,],[1,2,3,],[4,5,6]])

In [3]:
a

array([[6, 7, 8],
       [1, 2, 3],
       [4, 5, 6]])

In [11]:
a[0:3,2]

array([8, 3, 6])

In [18]:
b=np.arange(5,101,5).reshape(2,5,2)

In [19]:
b

array([[[  5,  10],
        [ 15,  20],
        [ 25,  30],
        [ 35,  40],
        [ 45,  50]],

       [[ 55,  60],
        [ 65,  70],
        [ 75,  80],
        [ 85,  90],
        [ 95, 100]]])

In [32]:
b[1,2,0:2]

array([75, 80])

In [34]:
d=np.arange(30).reshape(2,15)

In [35]:
d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [47]:
np.hsplit(d,5)

[array([[ 0,  1,  2],
        [15, 16, 17]]),
 array([[ 3,  4,  5],
        [18, 19, 20]]),
 array([[ 6,  7,  8],
        [21, 22, 23]]),
 array([[ 9, 10, 11],
        [24, 25, 26]]),
 array([[12, 13, 14],
        [27, 28, 29]])]

In [42]:
np.vsplit(d,2)

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])]

In [5]:
e=np.array([1,2,3,4,5,6,6,7])

In [6]:
e

array([1, 2, 3, 4, 5, 6, 6, 7])

In [18]:
np.split(e,[1,4])

[array([1]), array([2, 3, 4]), array([5, 6, 6, 7])]