In [2]:
import numpy as np


In [194]:
a=np.array([1,2,3,4,5])

In [198]:
a

array([1, 2, 3, 4, 5])

In [3]:
b=np.array([[1,2],[3,4],[5,6],[7,8]])

In [4]:
b

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [5]:
b.ndim

2

In [47]:
b.astype('f')

array([[1., 2.],
       [3., 4.],
       [5., 6.],
       [7., 8.]], dtype=float32)

In [48]:
a.ndim
b.ndim


2

In [49]:
b

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [50]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [51]:
np.arange(1,5,2)

array([1, 3])

In [52]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [53]:
b=np.array([[2,1],[4,3],[5,6],[8,7]])

In [54]:
b

array([[2, 1],
       [4, 3],
       [5, 6],
       [8, 7]])

In [55]:
b.min(axis=1)

array([1, 3, 5, 7])

In [56]:
b.sum()

36

In [57]:
b.sum(axis=0)

array([19, 17])

In [58]:
b.sum(axis=1)

array([ 3,  7, 11, 15])

In [59]:
b


array([[2, 1],
       [4, 3],
       [5, 6],
       [8, 7]])

In [60]:
a

array([1, 2, 3, 4, 5])

In [61]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])

In [62]:
a

array([[1, 2],
       [3, 4]])

In [63]:
b

array([[5, 6],
       [7, 8]])

In [64]:
a.dot(b)

array([[19, 22],
       [43, 50]])

In [65]:
a

array([[1, 2],
       [3, 4]])

In [66]:
b

array([[5, 6],
       [7, 8]])

In [72]:
c=np.ones((2,4,3))

In [73]:
c

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [82]:
f=np.arange(5,101,5)

In [154]:
f

array([  5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,
        70,  75,  80,  85,  90,  95, 100])

In [86]:
f.reshape(2,10,1)

array([[[  5],
        [ 10],
        [ 15],
        [ 20],
        [ 25],
        [ 30],
        [ 35],
        [ 40],
        [ 45],
        [ 50]],

       [[ 55],
        [ 60],
        [ 65],
        [ 70],
        [ 75],
        [ 80],
        [ 85],
        [ 90],
        [ 95],
        [100]]])

In [115]:
g=np.linspace(1,14)

In [116]:
g

array([ 1.        ,  1.26530612,  1.53061224,  1.79591837,  2.06122449,
        2.32653061,  2.59183673,  2.85714286,  3.12244898,  3.3877551 ,
        3.65306122,  3.91836735,  4.18367347,  4.44897959,  4.71428571,
        4.97959184,  5.24489796,  5.51020408,  5.7755102 ,  6.04081633,
        6.30612245,  6.57142857,  6.83673469,  7.10204082,  7.36734694,
        7.63265306,  7.89795918,  8.16326531,  8.42857143,  8.69387755,
        8.95918367,  9.2244898 ,  9.48979592,  9.75510204, 10.02040816,
       10.28571429, 10.55102041, 10.81632653, 11.08163265, 11.34693878,
       11.6122449 , 11.87755102, 12.14285714, 12.40816327, 12.67346939,
       12.93877551, 13.20408163, 13.46938776, 13.73469388, 14.        ])

In [119]:
a

array([[1, 2],
       [3, 4]])

In [120]:
a.ravel()

array([1, 2, 3, 4])

In [133]:
a.flatten(order='d')

ValueError: order must be one of 'C', 'F', 'A', or 'K' (got 'd')

In [182]:
a=np.arange(1,65).reshape(4,4,4)

In [183]:
a

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[17, 18, 19, 20],
        [21, 22, 23, 24],
        [25, 26, 27, 28],
        [29, 30, 31, 32]],

       [[33, 34, 35, 36],
        [37, 38, 39, 40],
        [41, 42, 43, 44],
        [45, 46, 47, 48]],

       [[49, 50, 51, 52],
        [53, 54, 55, 56],
        [57, 58, 59, 60],
        [61, 62, 63, 64]]])

In [192]:
a.reshape(16,-1)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32],
       [33, 34, 35, 36],
       [37, 38, 39, 40],
       [41, 42, 43, 44],
       [45, 46, 47, 48],
       [49, 50, 51, 52],
       [53, 54, 55, 56],
       [57, 58, 59, 60],
       [61, 62, 63, 64]])

In [174]:
a.ndim

3

In [193]:
a

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[17, 18, 19, 20],
        [21, 22, 23, 24],
        [25, 26, 27, 28],
        [29, 30, 31, 32]],

       [[33, 34, 35, 36],
        [37, 38, 39, 40],
        [41, 42, 43, 44],
        [45, 46, 47, 48]],

       [[49, 50, 51, 52],
        [53, 54, 55, 56],
        [57, 58, 59, 60],
        [61, 62, 63, 64]]])

In [212]:
a=np.arange(1,7).reshape(3,2)

In [211]:
b=np.arange(7,13).reshape(3,2)

In [213]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [214]:
b

array([[ 7,  8],
       [ 9, 10],
       [11, 12]])

In [215]:
c=a+b

In [216]:
c

array([[ 8, 10],
       [12, 14],
       [16, 18]])

In [217]:
c1=np.add(a,b)

In [218]:
c1

array([[ 8, 10],
       [12, 14],
       [16, 18]])

In [226]:
c2=np.sum(b,axis=1)

In [227]:
c2

array([15, 19, 23])

In [229]:
np.argmax(a)

5

In [230]:
d=np.array([[1,2],[9,6],[3,7]])

In [231]:
d

array([[1, 2],
       [9, 6],
       [3, 7]])

In [232]:
np.argmax(d)

2

In [254]:
c2

array([15, 19, 23])

In [255]:
b

array([[ 7,  8],
       [ 9, 10],
       [11, 12]])

In [265]:
e=np.arange(1,17).reshape(2,2,4)

In [266]:
e

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [283]:
np.trace(e)

array([14, 16, 18, 20])

In [268]:
a = np.arange(8).reshape((2,2,2))

In [269]:
a

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [270]:
np.trace(a)

array([6, 8])