In [1]:
import pandas as pd
import numpy as np
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.datasets import load_iris

In [2]:
data= load_iris()

In [3]:
data.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [4]:
df = pd.DataFrame(data.data , columns=data.feature_names)

In [5]:
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [6]:
df["target"]= data.target

In [7]:
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]

In [8]:
X = df.drop("target",axis=1)

In [9]:
y= df["target"]

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42) 

In [11]:
X_train.shape

(120, 4)

In [12]:
model = SVC()
model.fit(X_train, y_train)
model.score(X_test, y_test)

1.0

## Hyperparamter tuning manually :


In [13]:
cross_val_score(SVC(C=1.0,kernel='rbf',gamma='scale'), X , y , cv=3)

array([0.96, 0.98, 0.94])

In [14]:
cross_val_score(SVC(C=1.0,kernel='linear',gamma='scale'), X , y , cv=3)

array([1.  , 1.  , 0.98])

In [15]:
cross_val_score(SVC(C=10.0,kernel='rbf'), X , y , cv=3)

array([0.98, 1.  , 0.94])

In [16]:
cross_val_score(SVC(C=10.0,kernel='poly',degree=3), X , y , cv=3)

array([1.  , 0.92, 0.96])

## Creat lists of params

In [17]:
kval= ['rbf','linear']
cval=[1,10,20]


In [18]:
for i in kval:
    for j in cval:
        score =cross_val_score(SVC(C =j , kernel=i, gamma='scale'), X , y ,cv=3)
        print(i ,"-",j , ":",np.average(score))

rbf - 1 : 0.96
rbf - 10 : 0.9733333333333333
rbf - 20 : 0.98
linear - 1 : 0.9933333333333333
linear - 10 : 0.9733333333333333
linear - 20 : 0.9666666666666667


## GridSearchCV 

In [19]:
from sklearn.model_selection import GridSearchCV

In [38]:
clf = GridSearchCV(SVC(gamma='scale'), {'kernel':['rbf','linear', 'poly'], 'C':[1,10,20]}, cv=3 )

In [39]:
clf

GridSearchCV(cv=3, estimator=SVC(),
             param_grid={'C': [1, 10, 20], 'kernel': ['rbf', 'linear', 'poly']})

In [40]:
clf.fit(X, y)

GridSearchCV(cv=3, estimator=SVC(),
             param_grid={'C': [1, 10, 20], 'kernel': ['rbf', 'linear', 'poly']})

In [41]:
clf.cv_results_

{'mean_fit_time': array([0.00718355, 0.00718808, 0.003829  , 0.00716909, 0.00440526,
        0.0008901 , 0.00777555, 0.00335685, 0.00371687]),
 'std_fit_time': array([0.00282229, 0.00118348, 0.00328963, 0.00223754, 0.00334976,
        0.00125879, 0.00186713, 0.00253072, 0.0023741 ]),
 'mean_score_time': array([0.00217088, 0.00351389, 0.00552996, 0.00513299, 0.00370948,
        0.00587662, 0.00476782, 0.00562684, 0.00691549]),
 'std_score_time': array([0.00307009, 0.0033487 , 0.00183684, 0.002604  , 0.00329922,
        0.00416515, 0.00194373, 0.00155825, 0.00093458]),
 'param_C': masked_array(data=[1, 1, 1, 10, 10, 10, 20, 20, 20],
              mask=[False, False, False, False, False, False, False, False,
                    False],
        fill_value='?',
             dtype=object),
 'param_kernel': masked_array(data=['rbf', 'linear', 'poly', 'rbf', 'linear', 'poly',
                    'rbf', 'linear', 'poly'],
              mask=[False, False, False, False, False, False, False, Fals

In [42]:
final = pd.DataFrame(clf.cv_results_ )

In [43]:
final

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C  \
0       0.007184      0.002822         0.002171        0.003070       1   
1       0.007188      0.001183         0.003514        0.003349       1   
2       0.003829      0.003290         0.005530        0.001837       1   
3       0.007169      0.002238         0.005133        0.002604      10   
4       0.004405      0.003350         0.003709        0.003299      10   
5       0.000890      0.001259         0.005877        0.004165      10   
6       0.007776      0.001867         0.004768        0.001944      20   
7       0.003357      0.002531         0.005627        0.001558      20   
8       0.003717      0.002374         0.006915        0.000935      20   

  param_kernel                         params  split0_test_score  \
0          rbf      {'C': 1, 'kernel': 'rbf'}               0.96   
1       linear   {'C': 1, 'kernel': 'linear'}               1.00   
2         poly     {'C': 1, 'kernel': 'poly'}               0.98   
3          rbf     {'C': 10, 'kernel': 'rbf'}               0.98   
4       linear  {'C': 10, 'kernel': 'linear'}               1.00   
5         poly    {'C': 10, 'kernel': 'poly'}               1.00   
6          rbf     {'C': 20, 'kernel': 'rbf'}               0.98   
7       linear  {'C': 20, 'kernel': 'linear'}               1.00   
8         poly    {'C': 20, 'kernel': 'poly'}               1.00   

   split1_test_score  split2_test_score  mean_test_score  std_test_score  \
0               0.98               0.94         0.960000        0.016330   
1               1.00               0.98         0.993333        0.009428   
2               0.94               0.98         0.966667        0.018856   
3               1.00               0.94         0.973333        0.024944   
4               0.94               0.98         0.973333        0.024944   
5               0.92               0.96         0.960000        0.032660   
6               0.98               0.98         0.980000        0.000000   
7               0.94               0.96         0.966667        0.024944   
8               0.92               0.96         0.960000        0.032660   

   rank_test_score  
0                7  
1                1  
2                5  
3                3  
4                3  
5                7  
6                2  
7                5  
8                7

In [44]:
final1 =final[['params','mean_test_score','rank_test_score']]

In [45]:
final1.set_index("rank_test_score",inplace=True )

In [46]:
final1.sort_index()

params  mean_test_score
rank_test_score                                                
1                 {'C': 1, 'kernel': 'linear'}         0.993333
2                   {'C': 20, 'kernel': 'rbf'}         0.980000
3                   {'C': 10, 'kernel': 'rbf'}         0.973333
3                {'C': 10, 'kernel': 'linear'}         0.973333
5                   {'C': 1, 'kernel': 'poly'}         0.966667
5                {'C': 20, 'kernel': 'linear'}         0.966667
7                    {'C': 1, 'kernel': 'rbf'}         0.960000
7                  {'C': 10, 'kernel': 'poly'}         0.960000
7                  {'C': 20, 'kernel': 'poly'}         0.960000

In [47]:
final1.reset_index()

rank_test_score                         params  mean_test_score
0                7      {'C': 1, 'kernel': 'rbf'}         0.960000
1                1   {'C': 1, 'kernel': 'linear'}         0.993333
2                5     {'C': 1, 'kernel': 'poly'}         0.966667
3                3     {'C': 10, 'kernel': 'rbf'}         0.973333
4                3  {'C': 10, 'kernel': 'linear'}         0.973333
5                7    {'C': 10, 'kernel': 'poly'}         0.960000
6                2     {'C': 20, 'kernel': 'rbf'}         0.980000
7                5  {'C': 20, 'kernel': 'linear'}         0.966667
8                7    {'C': 20, 'kernel': 'poly'}         0.960000

In [48]:
from sklearn.model_selection import RandomizedSearchCV

### Just had one addition parameter n_iter=3 : This gives only top three result

In [49]:
clf = RandomizedSearchCV(SVC(gamma='scale'), {'kernel':['rbf','linear', 'poly'], 'C':[1,10,20]}, cv=3 , n_iter=3)

In [50]:
clf

RandomizedSearchCV(cv=3, estimator=SVC(), n_iter=3,
                   param_distributions={'C': [1, 10, 20],
                                        'kernel': ['rbf', 'linear', 'poly']})

In [51]:
clf.fit(X , y)

RandomizedSearchCV(cv=3, estimator=SVC(), n_iter=3,
                   param_distributions={'C': [1, 10, 20],
                                        'kernel': ['rbf', 'linear', 'poly']})

In [52]:
final2 = pd.DataFrame(clf.cv_results_)

In [53]:
final2

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_kernel  \
0       0.003319      0.000446         0.002551        0.001450         poly   
1       0.004073      0.000914         0.000509        0.000720          rbf   
2       0.002198      0.003108         0.006798        0.003604       linear   

  param_C                         params  split0_test_score  \
0      10    {'kernel': 'poly', 'C': 10}               1.00   
1      20     {'kernel': 'rbf', 'C': 20}               0.98   
2      20  {'kernel': 'linear', 'C': 20}               1.00   

   split1_test_score  split2_test_score  mean_test_score  std_test_score  \
0               0.92               0.96         0.960000        0.032660   
1               0.98               0.98         0.980000        0.000000   
2               0.94               0.96         0.966667        0.024944   

   rank_test_score  
0                3  
1                1  
2                2